// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZhCd6C9pXVNTIKTXEEpQFyEyZt-HDAEg',
    appId: '1:435909058123:web:7ab36134423eaa9ea037ce',
    messagingSenderId: '435909058123',
    projectId: 'codeverse-68172',
    authDomain: 'codeverse-68172.firebaseapp.com',
    storageBucket: 'codeverse-68172.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfaSEOTBFQVczHlFupyMgxggd-7engr3w',
    appId: '1:435909058123:android:6a4b4141f94cc4fba037ce',
    messagingSenderId: '435909058123',
    projectId: 'codeverse-68172',
    storageBucket: 'codeverse-68172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABZsfYvtoB1l64zfAeJ1JNLa6Y8JUzMg8',
    appId: '1:435909058123:ios:48a484b9d4dfa456a037ce',
    messagingSenderId: '435909058123',
    projectId: 'codeverse-68172',
    storageBucket: 'codeverse-68172.appspot.com',
    iosBundleId: 'com.example.codeverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABZsfYvtoB1l64zfAeJ1JNLa6Y8JUzMg8',
    appId: '1:435909058123:ios:48a484b9d4dfa456a037ce',
    messagingSenderId: '435909058123',
    projectId: 'codeverse-68172',
    storageBucket: 'codeverse-68172.appspot.com',
    iosBundleId: 'com.example.codeverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZhCd6C9pXVNTIKTXEEpQFyEyZt-HDAEg',
    appId: '1:435909058123:web:bae4df601fd0b44ba037ce',
    messagingSenderId: '435909058123',
    projectId: 'codeverse-68172',
    authDomain: 'codeverse-68172.firebaseapp.com',
    storageBucket: 'codeverse-68172.appspot.com',
  );
}
